"""delete_gmail_structure

Revision ID: 5c53a63ad1b4
Revises: c1d2e3f4a5b6
Create Date: 2026-09-15 01:23:03.315204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c53a63ad1b4'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_contacts_university_id'), table_name='university_contacts', if_exists=True)
    op.drop_index(op.f('ix_university_contacts_university_type'), table_name='university_contacts', if_exists=True)
    op.drop_table('university_contacts', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_gmail_thread'), table_name='university_email_messages', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_motivation_letter_id'), table_name='university_email_messages', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_university_id'), table_name='university_email_messages', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_university_status'), table_name='university_email_messages', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_user_id'), table_name='university_email_messages', if_exists=True)
    op.drop_index(op.f('ix_university_email_messages_user_status'), table_name='university_email_messages', if_exists=True)
    op.drop_table('university_email_messages', if_exists=True)
    op.create_index(op.f('ix_career_analyses_id'), 'career_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_career_education_id'), 'career_education', ['id'], unique=False)
    op.create_index(op.f('ix_career_insights_id'), 'career_insights', ['id'], unique=False)
    op.create_index(op.f('ix_career_roi_id'), 'career_roi', ['id'], unique=False)
    op.create_index(op.f('ix_career_salary_bands_id'), 'career_salary_bands', ['id'], unique=False)
    op.create_index(op.f('ix_career_salary_forecasts_id'), 'career_salary_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_career_scores_id'), 'career_scores', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_connections_id'), 'gmail_connections', ['id'], unique=False)
    op.create_index(op.f('ix_motivation_letters_id'), 'motivation_letters', ['id'], unique=False)
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.alter_column('roi_calculations', 'study_years',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=False,
               existing_server_default=sa.text('4'))
    op.create_index(op.f('ix_university_documents_id'), 'university_documents', ['id'], unique=False)
    op.create_index(op.f('ix_university_scholarships_id'), 'university_scholarships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_scholarships_id'), table_name='university_scholarships')
    op.drop_index(op.f('ix_university_documents_id'), table_name='university_documents')
    op.alter_column('roi_calculations', 'study_years',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('4'))
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_index(op.f('ix_motivation_letters_id'), table_name='motivation_letters')
    op.drop_index(op.f('ix_gmail_connections_id'), table_name='gmail_connections')
    op.drop_index(op.f('ix_career_scores_id'), table_name='career_scores')
    op.drop_index(op.f('ix_career_salary_forecasts_id'), table_name='career_salary_forecasts')
    op.drop_index(op.f('ix_career_salary_bands_id'), table_name='career_salary_bands')
    op.drop_index(op.f('ix_career_roi_id'), table_name='career_roi')
    op.drop_index(op.f('ix_career_insights_id'), table_name='career_insights')
    op.drop_index(op.f('ix_career_education_id'), table_name='career_education')
    op.drop_index(op.f('ix_career_analyses_id'), table_name='career_analyses')
    op.create_table('university_email_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivation_letter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=998), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('gmail_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gmail_thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['motivation_letter_id'], ['motivation_letters.id'], name=op.f('university_email_messages_motivation_letter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('university_email_messages_university_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('university_email_messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('university_email_messages_pkey'))
    )
    op.create_index(op.f('ix_university_email_messages_user_status'), 'university_email_messages', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_university_email_messages_user_id'), 'university_email_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_university_email_messages_university_status'), 'university_email_messages', ['university_id', 'status'], unique=False)
    op.create_index(op.f('ix_university_email_messages_university_id'), 'university_email_messages', ['university_id'], unique=False)
    op.create_index(op.f('ix_university_email_messages_motivation_letter_id'), 'university_email_messages', ['motivation_letter_id'], unique=False)
    op.create_index(op.f('ix_university_email_messages_gmail_thread'), 'university_email_messages', ['gmail_thread_id'], unique=False)
    op.create_table('university_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('contact_type', sa.VARCHAR(length=40), server_default=sa.text("'admissions'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('university_contacts_university_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('university_contacts_pkey')),
    sa.UniqueConstraint('university_id', 'email', name=op.f('uq_university_contacts_university_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_university_contacts_university_type'), 'university_contacts', ['university_id', 'contact_type'], unique=False)
    op.create_index(op.f('ix_university_contacts_university_id'), 'university_contacts', ['university_id'], unique=False)
    # ### end Alembic commands ###
