"""Add UserRoadmap

Revision ID: f497d7a630cb
Revises: 2a5f76e91674
Create Date: 2026-07-05 02:15:55.992326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f497d7a630cb'
down_revision: Union[str, Sequence[str], None] = '2a5f76e91674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roadmaps',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_job', sa.String(length=255), nullable=False),
    sa.Column('dreamwork_plan_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roadmaps_id'), 'user_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_user_roadmaps_user_id'), 'user_roadmaps', ['user_id'], unique=False)
    op.drop_column('universities', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_roadmaps_user_id'), table_name='user_roadmaps')
    op.drop_index(op.f('ix_user_roadmaps_id'), table_name='user_roadmaps')
    op.drop_table('user_roadmaps')
    # ### end Alembic commands ###
